brew "asmvik/formulae/yabai", trusted: true
brew "eugene-babichenko/fixit/fixit", trusted: true
# why is fuck not maintained on brew ugh
tap "felixkratz/formulae", trusted: true
tap "jackielii/tap"
tap "koekeishiya/formulae", "https://github.com/asmvik/homebrew-formulae.git"
tap "nailuogg/recoll", "https://github.com/nailuoGG/homebrew-recoll", trusted: true
tap "nikitabobko/tap", trusted: true
tap "shaunsingh/sfmono-nerd-font-ligaturized", "https://github.com/shaunsingh/homebrew-SFMono-Nerd-Font-Ligaturized"

brew "bat"
brew "btop"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fish"
brew "fzf"
brew "gcc"
brew "gh"
brew "git-delta"
brew "lazygit"
brew "lua"
brew "neovim"
brew "nowplaying-cli"
brew "ripgrep"
brew "rustup"
brew "sesh"
brew "stow"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "typst"
brew "uv"
brew "zoxide"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "nailuogg/recoll/recoll"

# Fonts
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-sf-mono"
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-sf-pro"

# Other casks
cask "karabiner-elements"
cask "kitty"
cask "ksnip"
cask "maccy"
cask "middleclick"
cask "sf-symbols"
cask "jackielii/tap/skhd-zig", trusted: true
cask "stats"

vscode "bourhaouta.tailwindshades"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "daviddai.deepseek-code-generator"
vscode "divyanshuagrawal.competitive-programming-helper"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "evan-buss.font-switcher"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.code-runner"
vscode "github.codespaces"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hjb2012.vscode-es6-string-html"
vscode "icrawl.discord-vscode"
vscode "james-yu.latex-workshop"
vscode "jumpinjackie.vscode-map-preview"
vscode "mathematic.vscode-latex"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-hub"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.extension-test-runner"
vscode "ms-vscode.remote-explorer"
vscode "myriad-dreamin.tinymist"
vscode "randomfractalsinc.geo-data-viewer"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "reditorsupport.r-syntax"
vscode "sidthesloth.html5-boilerplate"
vscode "surv.typst-math"
vscode "tecosaur.latex-utilities"
vscode "tomoki1207.pdf"
vscode "ukaisi.inspect-ai"
vscode "vadimcn.vscode-lldb"
vscode "vscjava.vscode-gradle"
vscode "wscats.cors-browser"
vscode "zarifprogrammer.tailwind-snippets"
