prSections:
  - title: my pull requests
    filters: is:open author:@me
    type: null
  - title: needs my review
    filters: is:open review-requested:@me
    type: null
  - title: involved
    filters: is:open involves:@me -author:@me
    type: null
issuesSections:
  - title: my issues
    filters: is:open author:@me
  - title: assigned
    filters: is:open assignee:@me
  - title: involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
  table:
    showSeparator: true
    compact: false
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#cba6f7"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#cba6f7"
      secondary: "#45475a"
      faint: "#313244"
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
