set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g mouse on
set -g history-limit 10000

# Rebind prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes
bind v split-window -h
bind s split-window -v

# Smart pane switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

